============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.3.0
rootdir: /home/jake/Development/mentat/tests/benchmarks/repos/exercism-python
configfile: pytest.ini
plugins: mock-3.11.1, reportlog-0.4.0, asyncio-0.21.1, xdist-3.3.1
asyncio: mode=strict
collected 12 items

exercises/practice/change/change_test.py .F..........                    [100%]

=================================== FAILURES ===================================
______________ ChangeTest.test_cannot_find_negative_change_values ______________

self = <change_test.ChangeTest testMethod=test_cannot_find_negative_change_values>

    def test_cannot_find_negative_change_values(self):
        with self.assertRaises(ValueError) as err:
            find_fewest_coins([1, 2, 5], -5)
        self.assertEqual(type(err.exception), ValueError)
>       self.assertEqual(err.exception.args[0], "target can't be negative")
E       AssertionError: 'target cannot be negative' != "target can't be negative"
E       - target cannot be negative
E       ?           ^^
E       + target can't be negative
E       ?           ^

exercises/practice/change/change_test.py:59: AssertionError
=========================== short test summary info ============================
FAILED exercises/practice/change/change_test.py::ChangeTest::test_cannot_find_negative_change_values
========================= 1 failed, 11 passed in 0.04s =========================
